from __future__ import annotations

from logging import Logger
from discord import Message
from discord.ext import commands
from crypex.localdata.localdata import LocalData
from crypex.cogs.utils.template_objects import TemplateObjects

Context: commands.Context = commands.Context

cogs: list[str]

def automatically_append_cogs() -> None: ...


class Crypex(commands.Bot):
    data: LocalData = ...
    templates: TemplateObjects = ...
    logger: Logger = ...
    launched: bool = ...
    default_prefix: str = ...
    def __init__(self, logger: Logger) -> None: ...
    def run(self) -> None: ...
    async def on_ready(self) -> None: ...
    async def on_message(self, message: Message) -> None: ...
    async def on_command_error(self, context: Context, exception: Exception) -> None: ...
