from discord.ext import commands
from typing import Any, Dict, Union, Tuple
from crypex.cogs.utils.template_objects import TemplateObjects

class Context(commands.Context):
    templates: TemplateObjects = ...
    def __init__(self, *args: Tuple[Any, ...], **kwargs: Dict[str, Any]) -> None: ...
    async def embed(self, **kwargs: Dict[str, Any]) -> None: ...
    async def get(self, **kwargs: Dict[str, Any]) -> None: ...
    async def edit(self, **kwargs: Dict[str, Any]) -> None: ...
