from discord.ext import commands
from typing import Any, Dict, Union
from crypex.cogs.utils.template_objects import TemplateObjects

class Context(commands.Context):
    templates: TemplateObjects = ...
    def __init__(self, *args: Dict[str, Any], **kwargs: Union[Dict[str, Any], str]) -> None: ...
    async def embed(self, **kwargs: Union[Dict[str, Any], str]) -> None: ...
