from typing import Union
from discord.ext import commands
from discord.ext.commands import Context
from discord import Member, TextChannel, User, VoiceChannel


class GuildManagement(commands.Cog):
    client: commands.Bot = ...
    def __init__(self, client: commands.Bot) -> None: ...
    async def create_channel(self, ctx: Context) -> None: ...
    async def delete_channel(self, ctx: Context, channel: Union[TextChannel, VoiceChannel],
                             *, reason: str=...) -> None: ...
    async def ban(self, ctx: Context, user: Union[Member, User, int], *, reason: str=...) -> None: ...
    async def unban(self, ctx: Context, user: Union[User, int], *, reason: str=...) -> None: ...
    async def kick(self, ctx: Context, user: Member, *, reason: str=...) -> None: ...
    async def mute(self, ctx: Context, user: Member, *, reason: str=...) -> None: ...
    async def unmute(self, ctx: Context, user: Member, *, reason: str=...) -> None: ...

def setup(client: commands.Bot) -> None: ...
