from __future__ import annotations

from logging import Logger
from typing import Any, Optional, Union

class LocalData:
    local_data: str = ...
    logger: Logger = ...
    def __init__(self, local_data: str = ...) -> None: ...
    def get(self, key: Union[str, Any]) -> list[Any]: ...
    def add(self, dictionary: dict[Any], add_to: Optional[str]=...) -> None: ...
    def edit(self, key: Union[str, Any], new_value: Union[str, Any], delete: bool=...) -> None: ...
