from discord.ext import commands

Context: commands.Context = commands.Context

class Sovereign(commands.Cog):
    client: commands.Bot = ...
    def __init__(self, client: commands.Bot) -> None: ...
    async def reload(self, ctx: Context, extension_name: str) -> None: ...
    async def shutdown(self, ctx: Context) -> None: ...

def setup(client: commands.Bot) -> None: ...
