from discord.ext import commands
from ..cogs.utils.context import Context

class Sovereign(commands.Cog):
    client: commands.Bot = ...
    def __init__(self, client: commands.Bot) -> None: ...
    async def reload(self, ctx: Context, extension_name: str) -> None: ...
    async def shutdown(self, ctx: Context) -> None: ...
    async def eval(self, ctx: Context, *, code: str) -> None: ...

def setup(client: commands.Bot) -> None: ...
