from __future__ import annotations

from typing import Optional
from discord import Colour, Color, Embed


class TemplateObjects:
    colors: list[Color, Colour] = ...
    def __init__(self) -> None: ...
    def get_color(self, color_name: str=..., random: bool=...) -> Optional[Colour]: ...
    def base_embed(self, text: str) -> Embed: ...
