from discord import Colour, Color, Embed
from typing import Optional, List


class TemplateObjects:
    colors: List[Color, Colour] = ...
    def __init__(self) -> None: ...
    def get_color(self, color_name: str=..., random: bool=...) -> Optional[Colour]: ...
    def base_embed(self, text: str) -> Embed: ...
