from discord import Member, User
from typing import Union, Optional
from ..cogs.utils.context import Context
from discord.ext.commands import Cog, Bot

class UserInteraction(Cog):
    client: Bot = ...
    def __init__(self, client: Bot) -> None: ...
    async def av(self, ctx: Context, user: Optional[Union[Member, User]] =...) -> None: ...

def setup(client: Bot) -> None: ...