from discord.ext import commands

class Crypt(commands.Cog):
    client: commands.Bot = ...
    def __init__(self, client: commands.Bot) -> None: ...

def setup(client: commands.Bot) -> None: ...
