from logging import Logger
from typing import List, Optional

class LocalData:
    local_data: str = ...
    logger: Logger = ...
    def __init__(self, local_data: str=...) -> None: ...
    def get(self, key: str) -> List[str]: ...
    def add(self, _d: dict, add_to: Optional[str]=...) -> None: ...
    def edit(self, key: str, new_value: str, delete: bool=...) -> None: ...
