from discord.ext import commands

class Sovereign(commands.Cog):
    client: commands.Bot = ...
    def __init__(self, client: commands.Bot) -> None: ...
    async def reload(self, ctx: commands.Context, extension_name: str) -> None: ...

def setup(client: commands.Bot) -> None: ...
