from discord import Color, Colour, Embed
from typing import Optional, List

class TemplateObjects:
    colors: List[Color] = ...
    def __init__(self) -> None: ...
    def get_color(self, color_name: Optional[str]) -> Optional[Colour]: ...
    def base_embed(self, text: str=...) -> Embed: ...
